/** Serializable execution-monitor domain contracts, independent of React and Runtime. */

export type ExecutionStatus = "queued" | "running" | "completed" | "failed" | "cancelled" | "retrying" | "unknown";
export type TimelineType = "execution_created" | "execution_started" | "node_started" | "node_completed" | "node_failed" | "retry_scheduled" | "retry_started" | "tool_started" | "tool_completed" | "provider_started" | "provider_completed" | "memory_access" | "plugin_execution" | "execution_completed" | "execution_failed" | "execution_cancelled" | "unknown";
export type LogLevel = "debug" | "info" | "warning" | "error" | "critical";
export type MonitorValue = string | number | boolean | null | readonly MonitorValue[] | { readonly [key: string]: MonitorValue };

export interface ExecutionSummary { readonly executionId: string; readonly workflowId: string; readonly projectId: string | null; readonly status: ExecutionStatus; readonly createdAt: string | null; readonly requestId: string | null; readonly error: string | null; }
export interface ExecutionTimelineEvent { readonly id: string; readonly type: TimelineType; readonly status: ExecutionStatus; readonly timestamp: string | null; readonly sequence: number; readonly nodeId: string | null; readonly message: string | null; readonly metadata: Readonly<Record<string, MonitorValue>>; }
export interface ExecutionTreeNode { readonly id: string; readonly parentId: string | null; readonly kind: "execution" | "workflow" | "node" | "tool" | "provider" | "memory" | "plugin" | "unknown"; readonly label: string; readonly status: ExecutionStatus; readonly durationMs: number | null; readonly error: string | null; readonly retryCount: number; readonly children: readonly ExecutionTreeNode[]; }
export interface ExecutionLogEntry { readonly id: string; readonly timestamp: string | null; readonly level: LogLevel; readonly message: string; readonly executionId: string; readonly workflowId: string | null; readonly nodeId: string | null; readonly traceId: string | null; readonly spanId: string | null; readonly metadata: Readonly<Record<string, MonitorValue>>; }
export interface ExecutionSpan { readonly spanId: string; readonly parentSpanId: string | null; readonly name: string; readonly kind: string; readonly status: ExecutionStatus; readonly startedAt: string | null; readonly endedAt: string | null; readonly durationMs: number | null; readonly attributes: Readonly<Record<string, MonitorValue>>; readonly errorType: string | null; }
export interface ExecutionTrace { readonly traceId: string; readonly rootSpanId: string | null; readonly spans: readonly ExecutionSpan[]; readonly startedAt: string | null; readonly endedAt: string | null; readonly durationMs: number | null; readonly status: ExecutionStatus; }
export interface ExecutionMetrics { readonly totalDurationMs: number | null; readonly nodeCount: number | null; readonly completedNodeCount: number | null; readonly failedNodeCount: number | null; readonly retryCount: number | null; readonly toolCallCount: number | null; readonly providerCallCount: number | null; readonly memoryOperationCount: number | null; readonly pluginCallCount: number | null; readonly logCount: number | null; readonly errorCount: number | null; }
export interface ExecutionSelection { readonly timelineEventId: string | null; readonly treeNodeId: string | null; }
export interface ExecutionFilter { readonly types: readonly TimelineType[]; readonly statuses: readonly ExecutionStatus[]; readonly logLevels: readonly LogLevel[]; readonly text: string; readonly nodeId: string | null; }
export interface ExecutionMonitorState { readonly executions: readonly ExecutionSummary[]; readonly activeExecution: ExecutionSummary | null; readonly timeline: readonly ExecutionTimelineEvent[]; readonly tree: ExecutionTreeNode | null; readonly logs: readonly ExecutionLogEntry[]; readonly trace: ExecutionTrace | null; readonly metrics: ExecutionMetrics | null; readonly filters: ExecutionFilter; readonly selection: ExecutionSelection; readonly loading: boolean; readonly error: string | null; readonly requestId: string | null; readonly lastRefreshedAt: string | null; }

export const emptyFilter: ExecutionFilter = { types: [], statuses: [], logLevels: [], text: "", nodeId: null };
export const initialExecutionMonitorState: ExecutionMonitorState = { executions: [], activeExecution: null, timeline: [], tree: null, logs: [], trace: null, metrics: null, filters: emptyFilter, selection: { timelineEventId: null, treeNodeId: null }, loading: false, error: null, requestId: null, lastRefreshedAt: null };
export const isTerminal = (status: ExecutionStatus): boolean => status === "completed" || status === "failed" || status === "cancelled";
