from typing import Protocol

from .quota import StorageDecision


class StoragePolicy(Protocol):
    def validate_bucket(self, value: object) -> StorageDecision: ...
    def validate_object(self, value: object) -> StorageDecision: ...
    def validate_context(self, value: object) -> StorageDecision: ...
    def validate_quota(self, value: object) -> StorageDecision: ...
    def validate_capability(self, value: object) -> StorageDecision: ...
