from typing import Protocol


class ExecutionPolicy(Protocol):
    def validate_creation(self, value: object) -> object: ...
    def validate_transition(self, value: object) -> object: ...
    def validate_context(self, value: object) -> object: ...
