"""Declarative deployment policy contract."""

from typing import Protocol

from .plan import DeploymentValidation


class DeploymentPolicy(Protocol):
    def validate_creation(self, value: object) -> DeploymentValidation: ...
    def validate_target(self, value: object) -> DeploymentValidation: ...
    def validate_strategy(self, value: object) -> DeploymentValidation: ...
    def validate_plan(self, value: object) -> DeploymentValidation: ...
    def validate_transition(self, value: object) -> DeploymentValidation: ...
    def validate_context(self, value: object) -> DeploymentValidation: ...
