"""Explicit Enterprise dependency boundaries."""

from __future__ import annotations

from typing import Protocol

from .models import UserRecord


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, digest: str) -> bool: ...


class UserDirectory(Protocol):
    def create_user(
        self, user: UserRecord, password: str, timestamp: str
    ) -> UserRecord: ...
    def update_user(self, user: UserRecord, timestamp: str) -> UserRecord: ...
    def suspend_user(self, user_id: str, timestamp: str) -> UserRecord: ...
    def restore_user(self, user_id: str, timestamp: str) -> UserRecord: ...
    def disable_user(self, user_id: str, timestamp: str) -> UserRecord: ...
    def verify_credentials(self, username: str, password: str) -> UserRecord: ...
    def get_user(self, user_id: str) -> UserRecord: ...
    def list_users(self) -> tuple[UserRecord, ...]: ...
