"""V7 Unified Resource Management Framework public API."""

from .contracts import (
    AllocationPlan,
    AuditEntry,
    Availability,
    Capacity,
    CapacityAnalysis,
    DependencyReference,
    RecoveryPlan,
    Reservation,
    ReservationConflict,
    Resource,
    ResourceConstraint,
    ResourceHealth,
    ResourceLifecycle,
    ResourceScope,
    ResourceType,
    ResourceTypeContract,
    ValidationIssue,
    ValidationReport,
)
from .framework import (
    GLOBAL_RESOURCE_FRAMEWORK,
    DependencyCycleError,
    IllegalLifecycleTransition,
    ReservationConflictError,
    ResourceCatalog,
    ResourceFramework,
    ResourceFrameworkError,
    ResourceRegistry,
    ResourceSecurity,
    ResourceValidationError,
)

__all__ = (
    "AllocationPlan",
    "AuditEntry",
    "Availability",
    "Capacity",
    "CapacityAnalysis",
    "DependencyCycleError",
    "DependencyReference",
    "GLOBAL_RESOURCE_FRAMEWORK",
    "IllegalLifecycleTransition",
    "RecoveryPlan",
    "Reservation",
    "ReservationConflict",
    "ReservationConflictError",
    "Resource",
    "ResourceCatalog",
    "ResourceConstraint",
    "ResourceFramework",
    "ResourceFrameworkError",
    "ResourceHealth",
    "ResourceLifecycle",
    "ResourceRegistry",
    "ResourceScope",
    "ResourceSecurity",
    "ResourceType",
    "ResourceTypeContract",
    "ResourceValidationError",
    "ValidationIssue",
    "ValidationReport",
)
