import { useEffect, useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import { type ApiListResponse, type EnterpriseRecord, type SearchEntry } from "./api";
import { useAuth } from "./auth";
import { Card, Loading, SearchBar, Table } from "./components";

export const dashboardPages = ["dashboard", "orchestrator", "execution-plans", "orchestrator-queues", "orchestrator-executions", "orchestrator-failures", "orchestrator-retries", "orchestrator-performance", "app-store", "app-store-categories", "app-store-details", "app-store-installed", "app-store-updates", "app-store-licenses", "app-store-subscriptions", "app-store-publishers", "app-store-reviews", "app-store-moderation", "app-store-analytics", "knowledge-bases", "collections", "documents", "ingestion", "knowledge-search", "knowledge-permissions", "connectors", "evaluation", "applications", "application-templates", "deployments", "application-usage", "application-versions", "application-permissions", "agents", "agent-runs", "plugins", "marketplace", "installed", "updates", "registry", "publishers", "packages", "downloads", "licenses", "reviews", "versions", "search", "statistics", "health", "users", "organizations", "tenants", "teams", "roles", "permissions", "license", "billing", "api-keys", "audit"] as const;
export const memoryDashboardPages = ["memory", "memory-namespaces", "memory-usage", "memory-retention", "memory-cache", "memory-retrieval", "memory-metrics"] as const;
export const reasoningDashboardPages = ["reasoning", "reasoning-plans", "reasoning-decisions", "reasoning-strategies", "reasoning-validation", "reasoning-metrics"] as const;
export const collaborationDashboardPages = ["collaboration", "collaboration-teams", "collaboration-projects", "collaboration-sessions", "collaboration-tasks", "collaboration-timeline", "collaboration-activity", "collaboration-notifications"] as const;
export const governanceDashboardPages = ["governance", "governance-policies", "governance-risks", "governance-compliance", "governance-approvals", "governance-controls", "governance-models", "governance-prompts", "governance-agents", "governance-applications", "governance-workflows", "governance-data", "governance-incidents", "governance-exceptions", "governance-reports"] as const;
export const modelDashboardPages = ["model-platform", "models", "model-providers", "model-profiles", "model-deployments", "model-routing", "model-fallback", "model-evaluations", "model-benchmarks", "model-usage", "model-cost", "model-governance"] as const;
export const securityDashboardPages = ["security", "security-identity", "security-authentication", "security-authorization", "security-secrets", "security-threats", "security-incidents", "security-compliance", "security-audit"] as const;
export const apiManagementDashboardPages = ["api-management", "api-management-apis", "api-management-gateways", "api-management-routes", "api-management-versions", "api-management-policies", "api-management-credentials", "api-management-rate-limits", "api-management-quotas", "api-management-subscriptions", "api-management-analytics", "api-management-developer-portal"] as const;
export const integrationHubDashboardPages = ["integration-hub", "integration-hub-catalog", "integration-hub-instances", "integration-hub-mappings", "integration-hub-flows", "integration-hub-credentials", "integration-hub-health", "integration-hub-schedules", "integration-hub-failures", "integration-hub-dead-letter", "integration-hub-analytics"] as const;
export const digitalTwinDashboardPages = ["digital-twins", "twin-topology", "twin-telemetry", "twin-simulation", "twin-predictions", "twin-optimization"] as const;
export const businessIntelligenceDashboardPages = ["business-intelligence-workspaces", "business-intelligence-data-sources", "business-intelligence-datasets", "business-intelligence-semantic-models", "business-intelligence-metrics", "business-intelligence-reports", "business-intelligence-dashboards", "business-intelligence-insights", "business-intelligence-alerts", "business-intelligence-subscriptions", "business-intelligence-governance"] as const;
export const commandCenterDashboardPages = ["command-center", "command-center-operations", "command-center-agents", "command-center-automation", "command-center-incidents", "command-center-alerts", "command-center-topology", "command-center-health", "command-center-activity", "command-center-audit"] as const;
export const tiktokDashboardPages = ["tiktok-account-center", "tiktok-browser-runtime", "tiktok-proxy-center", "tiktok-data-collection", "tiktok-ai-interaction-center"] as const;
export const knowledgeGraphDashboardPages = ["knowledge-graphs", "knowledge-graph-entities", "knowledge-graph-relationships", "knowledge-graph-ontology", "knowledge-graph-taxonomy", "knowledge-graph-lineage", "knowledge-graph-analytics", "knowledge-graph-queries"] as const;

function useRequest<T>(load: () => Promise<T>) {
  const [value, setValue] = useState<T | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; load().then((result) => { if (active) setValue(result); }).catch((reason: unknown) => { if (active) setError(reason instanceof Error ? reason.message : "Request failed."); }); return () => { active = false; }; }, []);
  return { value, error };
}

function RecordList({ title, load }: { title: string; load(): Promise<ApiListResponse<unknown>> }) {
  const { value, error } = useRequest(load);
  return <Card><h1>{title}</h1>{error && <p role="alert">{error}</p>}{!value && !error && <Loading />}{value && <Table><tbody>{value.data.map((item, index) => { const record = item as Record<string, unknown>; return <tr key={String(record.registry_id ?? record.publisher_id ?? record.package_id ?? record.version_id ?? index)}><td>{JSON.stringify(record)}</td></tr>; })}</tbody></Table>}</Card>;
}

export function LoginPage() {
  const { login, token } = useAuth(); const navigate = useNavigate(); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState<string | null>(null);
  if (token) return <Navigate to="/dashboard" replace />;
  return <Card><h1>Login</h1><form onSubmit={(event) => { event.preventDefault(); login({ username, password }).then(() => navigate("/dashboard")).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Login failed.")); }}><label>Username<input value={username} onChange={(event) => setUsername(event.target.value)} /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label><button type="submit">Sign in</button></form>{error && <p role="alert">{error}</p>}</Card>;
}

export function DashboardHome() {
  const { client } = useAuth();
  const version = useRequest(() => client.version());
  const health = useRequest(() => client.health());
  const statistics = useRequest(() => client.statistics());
  return <><h1>Dashboard</h1><div className="cards"><Card><h2>Server Version</h2><p>{version.value?.server_version ?? "Loading..."}</p></Card><Card><h2>Health Summary</h2><p>{health.value?.checks.length ?? "..."} checks</p></Card><Card><h2>Statistics Summary</h2><p>{statistics.value?.data.counters.total_records ?? "..."} records</p></Card></div></>;
}

export function RegistryPage() { const { client } = useAuth(); return <RecordList title="Registry" load={() => client.registries()} />; }
export function PublishersPage() { const { client } = useAuth(); return <RecordList title="Publishers" load={() => client.publishers()} />; }
export function PackagesPage() { const { client } = useAuth(); return <RecordList title="Packages" load={() => client.packages()} />; }
export function MarketplacePage() { const { client } = useAuth(); return <RecordList title="Enterprise Marketplace" load={() => client.marketplace()} />; }
export function DownloadsPage() { const { client } = useAuth(); return <RecordList title="Downloads" load={() => client.marketplaceDownloads()} />; }
export function LicensesPage() { const { client } = useAuth(); return <RecordList title="Licenses" load={() => client.marketplaceLicenses()} />; }
export function ReviewsPage() { const { client } = useAuth(); return <RecordList title="Reviews" load={() => client.marketplaceReviews()} />; }
export function VersionsPage() { const { client } = useAuth(); return <RecordList title="Versions" load={() => client.versions()} />; }
export function AgentDefinitionsPage() { const { client } = useAuth(); return <RecordList title="Agent Definitions" load={() => client.agents()} />; }
export function AgentRunsPage() { return <Card><h1>Agent Runs</h1><p>Open a run to inspect status, events, outputs, and metrics.</p></Card>; }
export function AgentRunDetailsPage() { return <Card><h1>Run Details</h1><p>Agent run events, outputs, and metrics are available through the run API.</p></Card>; }
export function PluginsPage({ title = "Plugins" }: { title?: string }) { const { client } = useAuth(); return <RecordList title={title} load={() => client.plugins()} />; }
export function PluginDetailsPage() { return <Card><h1>Plugin Details</h1><p>Review plugin metadata, lifecycle, tools, signing status, and requested permissions.</p></Card>; }
export function PluginPermissionsPage() { return <Card><h1>Plugin Permissions</h1><p>Filesystem, network, environment, secrets, API, database, workflow, and agent grants are shown here.</p></Card>; }
export function ApplicationsPage() { const { client } = useAuth(); return <RecordList title="AI Applications" load={() => client.applications()} />; }
export function ApplicationTemplatesPage() { const { client } = useAuth(); return <RecordList title="Application Templates" load={() => client.applicationTemplates()} />; }
export function ApplicationDeploymentsPage() { const { client } = useAuth(); return <RecordList title="Application Deployments" load={() => client.applicationDeployments()} />; }
export function ApplicationVersionsPage() { const { client } = useAuth(); return <RecordList title="Application Versions" load={() => client.applicationVersions()} />; }
export function ApplicationUsagePage() { const { client } = useAuth(); const state = useRequest(() => client.applicationDashboard()); return <Card><h1>Application Usage</h1>{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }
export function ApplicationPermissionsPage() { return <Card><h1>Application Permissions</h1><p>Manage view, edit, publish, deploy, run, and administrator grants.</p></Card>; }
export function KnowledgeBasesPage() { const { client } = useAuth(); return <RecordList title="Knowledge Bases" load={() => client.knowledgeBases()} />; }
export function CollectionsPage() { const { client } = useAuth(); return <RecordList title="Collections" load={() => client.knowledge("collections")} />; }
export function DocumentsPage() { const { client } = useAuth(); return <RecordList title="Documents" load={() => client.knowledge("documents")} />; }
export function KnowledgeStatusPage({ title }: { title: string }) { return <Card><h1>{title}</h1><p>Tenant-scoped enterprise knowledge controls and status.</p></Card>; }
export function AppStorePage({ title, resource = "" }: { title: string; resource?: string }) { const { client } = useAuth(); const state = useRequest(() => client.appStore(resource)); return <Card><h1>{title}</h1>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }
export function OrchestratorPage({ title = "Enterprise AI Orchestrator" }: { title?: string }) { const { client } = useAuth(); const state = useRequest(() => client.orchestrator()); return <Card><h1>{title}</h1>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }
export function ReasoningPage({ title = "Reasoning Sessions" }: { title?: string }) { const { client } = useAuth(); const state = useRequest(() => client.reasoning()); return <Card><h1>{title}</h1>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }
export function CollaborationPage({ title = "Enterprise AI Collaboration" }: { title?: string }) { const { client } = useAuth(); const state = useRequest(() => client.collaborationDashboard()); return <Card><h1>{title}</h1>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }
export function GovernancePage({ title = "Enterprise AI Governance" }: { title?: string }) { const { client } = useAuth(); const state = useRequest(() => client.governanceDashboard()); return <Card><h1>{title}</h1><p>Governance records support oversight workflows and do not claim certification or legal compliance.</p>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }
export function ModelPlatformPage({ title = "Enterprise AI Model Platform", resource = "model-platform" }: { title?: string; resource?: string }) { const { client } = useAuth(); const state = useRequest(() => client.modelPlatform(resource)); return <Card><h1>{title}</h1><p>Tenant-scoped model operations use credential references; secrets are never displayed.</p>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }
export function SecurityPlatformPage({ title = "Enterprise AI Security Platform", resource = "dashboard" }: { title?: string; resource?: string }) { const { client } = useAuth(); const state = useRequest(() => client.security(resource)); return <Card><h1>{title}</h1><p>Tenant-scoped zero-trust controls expose references and security posture without revealing credentials.</p>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }
export function ApiManagementPage({ title = "Enterprise AI API Management", resource = "dashboard" }: { title?: string; resource?: string }) { const { client } = useAuth(); const state = useRequest(() => client.apiManagement(resource)); return <Card><h1>{title}</h1><p>Tenant-scoped API lifecycle, gateway, policy, credential-reference, subscription, quota, and analytics controls.</p>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }
export function IntegrationHubPage({ title = "Enterprise AI Integration Hub", resource = "analytics" }: { title?: string; resource?: string }) { const { client } = useAuth(); const state = useRequest(() => client.integrationHub(resource)); return <Card><h1>{title}</h1><p>Tenant-scoped connector catalog, instances, declarative mappings, flows, credential references, health, schedules, failures, and analytics.</p>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }
export function DigitalTwinPage({ title = "Enterprise AI Digital Twin Platform", resource = "digital-twins" }: { title?: string; resource?: string }) { const { client } = useAuth(); const state = useRequest(() => client.digitalTwin(resource)); return <Card><h1>{title}</h1><p>Tenant-scoped twins, topology, telemetry, simulation, predictions, and optimization with versioned state and audited lifecycle controls.</p>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }
export function BusinessIntelligencePage({ title = "Enterprise AI Business Intelligence Platform", resource = "workspaces" }: { title?: string; resource?: string }) { const { client } = useAuth(); const state = useRequest(() => client.businessIntelligence(resource)); return <Card><h1>{title}</h1><p>Tenant-scoped workspaces, governed semantic models, bounded analytics, reports, dashboards, insights, alerts, and subscriptions.</p>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }
export function CommandCenterPage({ title = "Enterprise AI Command Center", resource = "overview" }: { title?: string; resource?: string }) { const { client } = useAuth(); const state = useRequest(() => client.commandCenter(resource)); return <Card><h1>{title}</h1><p>Unified tenant-scoped control planes, live operations, incident response, topology, health, activity, and audit.</p>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }
export function KnowledgeGraphPage({ title = "Enterprise AI Knowledge Graph", resource = "graphs" }: { title?: string; resource?: string }) { const { client } = useAuth(); const state = useRequest(() => client.knowledgeGraph(resource)); return <Card><h1>{title}</h1><p>Tenant-scoped graphs, entities, relationships, semantics, lineage, bounded queries, reasoning, and analytics.</p>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }
export function TikTokBrowserRuntimePage() { const { client } = useAuth(); const state = useRequest(() => client.tiktokBrowserRuntime()); return <Card><h1>TikTok Browser Runtime</h1><p>Tenant-scoped browser instances, profiles, account bindings, pool, queue, health, encrypted sessions, storage, and bounded recovery.</p>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }
export function TikTokProxyCenterPage() { const { client } = useAuth(); const state = useRequest(() => client.tiktokProxyCenter()); return <Card><h1>TikTok Proxy Center</h1><p>Tenant-scoped inventory, health, regions, countries, groups, bindings, pool, queue, statistics, and failure operations. Credentials remain secret references.</p>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }
export function TikTokAccountCenterPage() { const { client } = useAuth(); const state = useRequest(() => client.tiktokDashboard()); return <Card><h1>TikTok Account Center</h1><p>Tenant-scoped accounts, login health, risk, groups, tags, sessions, cookies, and browser bindings.</p>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }
export function TikTokDataCollectionPage() { const { client } = useAuth(); const state = useRequest(() => client.tiktokDataCollection()); return <Card><h1>TikTok Data Collection Center</h1><p>Tenant-scoped projects, jobs, datasets, pipelines, execution history, analytics, and encrypted storage references. Collection runs only through configured platform adapters.</p>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }
export function TikTokInteractionCenterPage() { const { client } = useAuth(); const state = useRequest(() => client.tiktokInteractionCenter()); return <Card><h1>TikTok AI Interaction Center</h1><p>Projects, tasks, drafts, localized templates, review and approval queues, analytics, history, statistics, and notifications with strict tenant isolation.</p>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }
export function MemoryPage({ title = "Memory Overview", resource = "memory" }: { title?: string; resource?: "memory" | "namespaces" | "cache" }) { const { client } = useAuth(); const state = useRequest<unknown>(() => resource === "namespaces" ? client.memoryNamespaces() : resource === "cache" ? client.memoryCache() : client.memories()); return <Card><h1>{title}</h1>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value, null, 2)}</pre> : <Loading />}</Card>; }

export function SearchPage() {
  const { client } = useAuth(); const [keyword, setKeyword] = useState(""); const [target, setTarget] = useState(""); const [results, setResults] = useState<ApiListResponse<SearchEntry> | null>(null); const [error, setError] = useState<string | null>(null);
  const submit = () => { client.search(keyword, target).then(setResults).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Search failed.")); };
  return <Card><h1>Search</h1><SearchBar value={keyword} onChange={setKeyword} onSubmit={submit} /><label>Target<select value={target} onChange={(event) => setTarget(event.target.value)}><option value="">All</option><option value="registry">Registry</option><option value="publisher">Publisher</option><option value="package">Package</option><option value="version">Version</option></select></label>{error && <p role="alert">{error}</p>}{results && <p>{results.total} results</p>}</Card>;
}

export function StatisticsPage() { const { client } = useAuth(); const state = useRequest(() => client.statistics()); return <Card><h1>Statistics</h1>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value.data.counters, null, 2)}</pre> : <Loading />}</Card>; }
export function HealthPage() { const { client } = useAuth(); const state = useRequest(() => client.health()); return <Card><h1>Health</h1>{state.error && <p role="alert">{state.error}</p>}{state.value ? <pre>{JSON.stringify(state.value.statistics, null, 2)}</pre> : <Loading />}</Card>; }
export function EnterprisePage({ title, load }: { title: string; load(): Promise<ApiListResponse<EnterpriseRecord>> }) { const state = useRequest(load); return <Card><h1>{title}</h1>{state.error && <p role="alert">Unauthorized or unavailable: {state.error}</p>}{!state.value && !state.error && <Loading />}{state.value && (state.value.total ? <Table><tbody>{state.value.data.map((item,index) => <tr key={index}><td>{JSON.stringify(item)}</td></tr>)}</tbody></Table> : <p>No records.</p>)}</Card>; }
export function NotFoundPage() { return <Card><h1>404</h1><p>Page not found.</p></Card>; }
